---
- name: Testing Code
  hosts: localhost
  tasks: 
  - name: Running Local Test
    shell: | 
            docker run --rm gesellix/trufflehog  https://github.com/mdhack0316/cnawebapp   >  status.txt 
