---
- name: Test HTTP Status Code 200
  hosts: localhost
  tasks:
    - name: Perform HTTP GET request
      uri:
        url: "http://localhost"
        method: GET
        return_content: no
        status_code: 200
      register: response
      ignore_errors: yes


    - name: Detailed Info
      debug:
        var: response

    - name: Check HTTP status code
      debug:
        msg: "HTTP Status Code: {{ response.status }}"
